server:
  port: 18791
  
spring:
  application:
    name: data-node-group-1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18771/eureka
      
service:
  serviceManager:
    name: data-node-1
    
application:
  mainNodeManager:
    topology:
      map:
        backupCount: 3